runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /fonts
  static_dir: fonts

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /layouts
  static_dir: layouts
  
- url: /images
  static_dir: images

- url: /download
  static_dir: download

- url: /base/.*
  script: base.app

- url: /demo_ccp/*
  script: chakma.app

- url: /bax/.*
  script: bamum.app

- url: /bod/.*
  script: tibetan.app

- url: /bsq/.*
  script: bassa.app

- url: /bts/.*
  script: bataksimalungun.app

- url: /cja/.*
  script: cham.app

- url: /ccp/.*
  script: chakma.app

- url: /chr/.*
  script: cherokee.app

- url: /demo_chr/.*
  script: cherokee.app

- url: /del/*
  script: lenape.app

- url: /demo_win/*
  script: hochunk.app

- url: /emoji/*
  script: emoji.app

- url: /tavt/.*
  script: taivietscript.app

- url: /win/.*
  script: hochunk.app

- url: /aho/.*
  script: ahom.app

- url: /kyu/.*
  script: kayah.app

- url: /lampung/.*
  script: lampung.app

- url: /lep/.*
  script: lepcha.app

- url: /men/.*
  script: mendekikakui.app

- url: /mez/.*
  script: menoninee.app

- url: /my/.*
  script: burmese.app

- url: /nv/.*
  script: navajo.app

- url: /one/.*
  script: oneida.app

- url: /phk/.*
  script: phake.app

- url: /rhg/.*
  script: rohingya.app

- url: /syl/.*
  script: sylheti.app

- url: /tai/.*
  script: ahom.app

- url: /zag/.*
  script: zaghawa.app
  

- url: /kb/.*
  script: keyboard.app

- url: /games/.*
  script: games.app

- url: /test/.*
  script: test.app

- url: /feedback/*
  script: feedback.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: latest
